deutschland/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views_dt
from .views_dt import zahltag,archiv

app_name = "de"

urlpatterns = [
    url(r'^$', views_dt.index, name="index"),
    url(r'^zahltag/(?P<pk>[-\d]+)/$', zahltag.as_view(), name="zahltag"),
    url(r'^archiv/$', archiv.as_view(), name="archiv"),
    url(r'^generator/$', views_dt.generator, name="generator"),
    url(r'^generator/neu/$', views_dt.parsen, name="neu"),
    url(r'^generator/get-datum/$', views_dt.getzahlen, name="checkdatum"),
]

lotto/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from start import views
from deutschland import views_dt
from europa import views_eu

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name="startpage"),
    url(r'^login/$', views.signin, name="login"),
    url(r'^signup/$', views.signup, name="register"),
    url(r'^signout/$', views.signout, name="signout"),
    url(r'^doregister/$', views.doReg, name="doreg"),
    url(r'^dologin/$', views.dologin, name="dologin"),
    url(r'^mailcheck/$', views.mailcheck, name="mailcheck"),
    url(r'^namecheck/$', views.namecheck, name="namecheck"),
    url(r'^user/(?P<uname>[-\w]+)/$', views.settings, name="einstellungen"),
    url(r'^doedit/$', views.doedit, name="doedit"),
    url(r'^de/', include('deutschland.urls')),
    url(r'^eu/', include('europa.urls')),
]

start/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
]

start/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
    
class einstellungen(models.Model):
    uname = models.CharField(primary_key=True,max_length=150,unique=True)
    deanzahl = models.PositiveSmallIntegerField(default=1)
    ziehung = models.PositiveSmallIntegerField(default=1)
    euanzahl = models.PositiveSmallIntegerField(default=1)
    datum = models.DateTimeField(default=datetime.datetime.now())
    
    def __str__(self):
        out = str(self.uname) + " (Letze Aktualisierung am: "+str(self.datum)+")"
        return out

start/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect, response
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.models import User
from .models import einstellungen
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response
import datetime
# Create your views here.
def index(request):
    context = {
        'title': "Startseite der Lotterie",
        'description': "Die Seite zum Vergleichen und Spielen!"
    }
    if request.user.is_authenticated():
        logedin = request.COOKIES.get('user_login')
        if not logedin:
            return HttpResponseRedirect("/signout/")
        else:
            return render(request,"lotto/start.html",context)
    else:
        return render(request,"lotto/start.html",context)

def signin(request):
    context = {
        'title': "Die Loginseite",
        'description': "Benutzerloginbereich.",
        'nbar': "login",
    }
    return render(request,"lotto/login.html",context)

@login_required
def signout(request):
    context = {
        'title': "",
        'description': "",
        'nbar': "logout",
    }
    site = render(request, 'lotto/logged.html')
    site.delete_cookie(key='user_login')
    logout(request)
    return site

def signup(request):
    if request.user.is_authenticated():
        fehler ="Du bist ja schon eingeloggt! Falls dies ein Fehler ist - leere dein Browsercache und -cookies!"
        context = {
            'title': "Benutzerregistrierung",
            'description': "Erstelle ein Profil und speichere deine Glückszahlen!.",
            'fehler': fehler,
        }
        return render(request, "lotto/fehler.html", context)
    else:
        context = {
            'title': "Benutzerregistrierung",
            'description': "Erstelle ein Profil und speichere deine Glückszahlen!.",
            'nbar': "register",
        }
        return render(request,"lotto/register.html",context)

def doReg(request):
    fehler = ""
    context = {
        'title': "Benutzerregistrierung",
        'description': "Erstelle ein Profil und speichere deine Glückszahlen!.",
        'fehler': fehler,
    }
    if request.POST:
        username = request.POST['name']
        userpass = request.POST['pw1']
        usermail = request.POST['email']
        if userpass != request.POST['pw2']:
            fehler ="Die Passwörter stimmen nich überein!"
            context = {
                'title': "Benutzerregistrierung",
                'description': "Erstelle ein Profil und speichere deine Glückszahlen!.",
                'fehler': fehler,
            }
            return render(request, "lotto/fehler.html", context)
        elif userpass == "" or userpass == None:
            fehler = "Passwort darf nicht leer sein!"
            context = {
                'title': "Benutzerregistrierung",
                'description': "Erstelle ein Profil und speichere deine Glückszahlen!.",
                'fehler': fehler,
            }
            return render(request, "lotto/fehler.html", context)
        elif usermail == "" or usermail == None:
            fehler = "E-Mail darf nicht leer sein!"
            context = {
                'title': "Benutzerregistrierung",
                'description': "Erstelle ein Profil und speichere deine Glückszahlen!.",
                'fehler': fehler,
            }
            return render(request, "lotto/fehler.html", context)
        elif username == "" or username == None:
            fehler = "Benutzername darf nicht leer sein!"
            context = {
                'title': "Benutzerregistrierung",
                'description': "Erstelle ein Profil und speichere deine Glückszahlen!.",
                'fehler': fehler,
            }
            return render(request, "lotto/fehler.html", context)
        else:
            new_user = User.objects.create_user(username, usermail, userpass)
            return HttpResponseRedirect('/login/')
    else:
        fehler ="Die Registrierung ist fehlgeschlagen!"
        context = {
            'title': "Benutzerregistrierung",
            'description': "Erstelle ein Profil und speichere deine Glückszahlen!.",
           'fehler': fehler,
        }
        return render(request, "lotto/fehler.html", context)

def dologin(request):
    username = request.POST['name']
    userpass = request.POST['pw1']
    user = authenticate(username=username,password=userpass)
    
    if user is not None:
        if user.is_active:
            site = render(request, 'lotto/logged.html')
            site.set_cookie(key='user_login', value=username)
            login(request, user)
            return site
        else: 
            fehler ="Anscheinend wurde Ihr Acoount gesperrt! Wenden Sie sich and den Admin!"
            context = {
                'title': "Einloggen fehlgeschlagen!",
                'description': "Irgendwas lief schief beim Einloggen!.",
               'fehler': fehler,
            }
            return render(request, "lotto/fehler.html", context)
    else:
        fehler ="Passwort oder Benutzername wurden falschen eingegeben!"
        context = {
            'title': "Einloggen fehlgeschlagen!",
            'description': "Irgendwas lief schief beim Einloggen!.",
           'fehler': fehler,
        }
        return render(request, "lotto/fehler.html", context)

def mailcheck(request):
    if request.GET:
        usermail = request.GET['email']
        mails = User.objects.filter(email=usermail)
        if mails.count() <= 0:
            return HttpResponse("ok", content_type="text/html")
        elif mails.email == usermail:
            return HttpResponse("same", content_type="text/html")
        else:
            return HttpResponse("no", content_type="text/html")
    else:
        pass

def namecheck(request):
    if request.GET:
        username = request.GET['name']
        names = User.objects.filter(username=username)
        if names.count() <= 0:
            return HttpResponse("ok", content_type="text/html")
        else:
            return HttpResponse("no", content_type="text/html")
    else:
        pass

@login_required
def settings(request, uname):
    if request.user.is_authenticated():
        user = User.objects.get(username=uname)
        username = user.username
        logedin = request.COOKIES.get('user_login')
        if username == logedin:
            usermail = user.email
            trusted = True
        else:
            usermail = "********"
            trusted = False
        userreg = user.date_joined
        userlast = user.last_login
        einstellungen.objects.get_or_create(uname=username)
        ben = einstellungen.objects.get(uname=username)
        euro = ben.euanzahl
        detl = ben.deanzahl
        ziehung = ben.ziehung
        
        context = {
            'title': "Benutzereinstellungen von "+username,
            'description': "Interne Seite jedes Benutzers",
            'login': username,
            'email': usermail,
            'regdate': userreg,
            'lastvisit': userlast,
            'trust': trusted,
            'de': detl,
            'ziehung': ziehung,
            'eu': euro,
            'nbar': "profil",
        }
        
        return render(request,"lotto/settings.html",context)
    else:
        return HttpResponseRedirect("/login/")

@login_required
def doedit(request):
    if request.user.is_authenticated():
        if request.POST:
            user = request.POST['user_login']
            de = request.POST['de']
            eu = request.POST['eu']
            ziehung = request.POST['ziehung']
            mail = request.POST['email']
            upass = request.POST['pw']
            
            user_set = einstellungen.objects.get(uname=user)
            user_set.deanzahl = de
            user_set.euanzahl = eu
            user_set.ziehung = ziehung
            user_set.datum = datetime.datetime.now()
            user_set.save()
            
            user_prof = User.objects.get(username=user)
            user_prof.email = mail
            if len(upass) > 0:
                user_prof.set_password(upass)
            else: 
                pass
            user_prof.save()
            
            return HttpResponseRedirect('/user/'+user+"/")
            
        else:
            pass

templates/lotto/basis.html
<!DOCTYPE html>
<html lang="de">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <title>{{title}}</title>
    <meta name="description" content="{{description}}">
    <link href="{% static 'css/bootstrap-purple-blue.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Lato:100,300,400,700,100italic,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    {% block styles %}{% endblock %}
</head>

<body>
	<nav>
		<ul class="nav nav-pills nav-justified nav-tabs-darker">
	        <li class="{% if nbar == 'home' %}active{% endif %}"><a href="{% url 'de:index' %}"><i class="fa fa-home"></i> Startseite</a></li>
	        <li class="{% if nbar == 'generator' %}active{% endif %}"><a href="{% url 'de:generator' %}"><i class="fa fa-list-alt"></i> Generator</a></li>
	        <li class="{% if nbar == 'archiv' %}active{% endif %}"><a href="{% url 'de:archiv' %}"><i class="fa fa-list"></i> Archiv</a></li>
	        {% if user.is_authenticated %}
	        	<li class="{% if nbar == 'profil' %}active{% endif %}"><a href="{% url 'einstellungen' uname=request.user.username %}"><i class="fa fa-address-card"></i> Profil</a></li>
	        	<li class="{% if nbar == 'logout' %}active{% endif %}"><a href="{% url 'signout' %}"><i class="fa fa-sign-out"></i> Ausloggen</a></li>
	        {% else %}
		        <li class="{% if nbar == 'login' %}active{% endif %}"><a href="{% url 'login' %}"><i class="fa fa-sign-in"></i> Einloggen</a></li>
		        <li class="{% if nbar == 'register' %}active{% endif %}"><a href="{% url 'register' %}"><i class="fa fa-user-plus"></i> Registrieren</a></li>
		    {% endif %}
	    </ul>
	</nav>
	<div class="container">
		{% block content %}
		<!-- OK -->
		{% endblock %}
	</div>
    <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
    {% block scripts %}{% endblock %}
</body>

</html>

templates/lotto/fehler.html
{% extends 'lotto/basis.html' %}
	{% block content %}
		<div class="alert alert-danger" role="alert">
		  <h1>Hoppla! Ein Fehler!</h1>
		  <p>{{fehler}}</p>
		</div>
	{% endblock %}

templates/lotto/generator.html
{% extends "lotto/basis.html" %}
	{% load staticfiles %}
	{% block styles %}
		<link href="{% static 'css/datepicker.min.css' %}" rel="stylesheet">
		<link href="{% static 'css/bootstrap-tour.min.css' %}" rel="stylesheet">
	{% endblock %}
	{% block content %}
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Lottozahlengenerator <button id="anleitung" type="button" class="btn btn-sm btn-info">Anleitung</button></h3>
			</div>
			<div class="panel-body">
				<div class="">
					<div class="panel panel-default col-md-6">
						<div class="panel-heading">
							<h3 class="panel-title">Wählen Sie das Spieldatum aus</h3>
						</div>
						<div class="panel-body table-responsive">
							<div class="form-group">
								<label for="tagzieh">Ziehtage berücksichtigen</label>
								<select name="tagzieh" id="tagzieh" class="form-control">
								</select>
							</div>
							<div class='input-group date'>
							    <span class="input-group-btn">
									<button class="btn btn-default bootstrap-touchspin-down" type="button" id="new_zahlen" data-toggle="tooltip" title="Prüft, ob neue Zahlen gibt und fügt diese der Datenbank hinzu"><i class="fa fa-bars" aria-hidden="true"></i> Aktualisieren</button>
								</span>
							    <input data-range="true" data-multiple-dates-separator=" - " id="dtdt" type="text" class="form-control datepicker-here" value="" style="cursor: pointer;" data-toggle="tooltip" title="Klicken, um Datum auszuwählen">
							</div>
						</div>
						<div class="panel-heading">
							<h3 class="panel-title">Wählen Sie 6 Zahlen aus</h3>
						</div>
						<div class="panel-body table-responsive">
							<table class="table table-bordered table-gen">
							</table>
							<div class="form-group">
								<div class="input-group bootstrap-touchspin">
									<span class="input-group-btn">
										<button class="btn btn-success bootstrap-touchspin-down" type="button" id="add_list" data-toggle="tooltip" title="Dem leeren Spielfeld die Glückszahlen hinzufügen"><i class="fa fa-arrow-circle-o-right" aria-hidden="true"></i> Hinzufügen</button>
									</span>
									<span class="input-group-addon bootstrap-touchspin-prefix" style="display: none;"></span>
									<input name="temp" id="temp" placeholder="Ihre gewählten Zahlen" class="form-control" readonly style="display: block;" data-toggle="tooltip" title="Diese Zahlen werden dem Spielfeld hinzugefügt">
									<span class="input-group-addon bootstrap-touchspin-postfix" id="temp_len" data-toggle="tooltip" title="Gibt Anzahl der übriggebliebenen Zahlen an">6</span>
									<span class="input-group-btn">
										<button id="clear_list" class="btn btn-danger bootstrap-touchspin-up" type="button" data-toggle="tooltip" title="Leert den Zwischenspeicher mit den Glückszahlen"><i class="fa fa-times" aria-hidden="true"></i> Leeren</button>
									</span>
								</div>
							</div>
						</div>
						<div class="panel-heading">
							<h3 class="panel-title">Wählen Sie Ihre Superzahl aus</h3>
						</div>
						<div class="panel-body table-responsive">
							<table class="table table-bordered table-super">
							</table>
						</div>
					</div>
					<div class="col-md-6">
						<div class="panel panel-default" id="meinewahl">
							<div class="panel-heading">
								<h3 class="panel-title">Ihre Wahl</h3>
							</div>
							<div class="panel-body">
								<ul class="list-group" id="list">
								</ul>
								<ul class="list-group" id="super">
									<li data-id="sz" class="list-group-item">
										<strong>Ihre Superzahl: </strong>
										<span data-feld="sz" id="feld-sz"></span>
									</li>
								</ul>
							</div>
							<div class="panel-footer">
								<div class="pull-right">
									<button id="rand" type="button" class="btn btn-cyanide">
										<i class="fa fa-random" aria-hidden="true"></i> Zufallszahlen
									</button>
									<button id="add" type="button" class="btn btn-success">
										<i class="fa fa-plus" aria-hidden="true"></i> Feld hinzufügen
									</button>
									<button id="del" type="button" class="btn btn-danger">
										<i class="fa fa-times" aria-hidden="true"></i> Feld entfernen
									</button>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="panel-heading">
				<h3 class="panel-title">Statistik</h3>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-10">
						<ul class="list-group statistik">
							<li class="list-group-item tickets"><span class="badge" id="ticket">0,35 &euro;</span><strong>Gebühren für Tickets (1€ pro Ticket):</strong></li>
							<li class="list-group-item felder"><span class="badge" id="gebuehren">1 &euro;</span><strong>Gebühren für Felder (0,35€ pro Feld):</strong></li>
							<li class="list-group-item gewinn"><span class="badge" id="gewinn">0 &euro;</span><strong>Gewinn:</strong></li>
						</ul>
						
					</div>
					<div class="col-md-2 vrgllll" data-toggle="tooltip" title="Bitte, erst Datum wählen, dann vergleichen">
						<button id="vergleichen" class="btn btn-primary btn-block">Vergleichen</button>
					</div>
				</div>
			</div>
		</div>
		<div class="modal fade" tabindex="-1" role="dialog" id="vrgl">
		    <div class="modal-dialog modal-lg" role="document">
		        <div class="modal-content">
		            <div class="modal-header">
		                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		                <h4 class="modal-title">Vergleichsergebnisse für <span class="datum"></span></h4>
		            </div>
		            <div class="modal-body">
			            <ul class="nav nav-tabs" role="tablist" id="tage">
			            </ul>
			            <div class="tab-content" id="tage_cont">
			            		
			            </div>
		            </div>
		            <div class="modal-footer">
		                <button type="button" class="btn btn-default" data-dismiss="modal">Schließen</button>
		            </div>
		        </div>
		    </div>
		</div>
	{% endblock %}
	{% block scripts %}
		<script src="http://static.maxim-harder.de/extra/gritter/jquery.gritter.min.js"></script>
		<script src="{% static "js/datepicker.min.js" %}"></script>
		<script src="{% static "js/datepicker.de.js" %}"></script>
		<script src="{% static 'js/moment.min.js' %}"></script>
		<script src="{% static 'js/moment.de.js' %}"></script>
		<script src="{% static 'js/bootstrap-tour.min.js' %}"></script>
		<script type="text/javascript">
		var felder = {{anzahl}}
		var zieh = {{ziehung}}
		</script>
    	<script type="text/javascript" src="{% static "js/gen-scripts.js" %}"></script>
	{% endblock %}

templates/lotto/index.html
{% extends "lotto/basis.html" %}
	{% block content %}
	<div class="jumbotron">
		<h1>{{title}}</h1>
		<small>{{description}}</small>
		<p>Um mit der Lotterie fortzufahren, muss man zuerst die Grundeinstellungen durchgehen. Erst dann wird das Archiv zur Verfügung stehen und der Generator selbst.</p>
		<p>
			{% if user.is_authenticated %}
				<a href="{% url 'einstellungen' uname=request.user.username %}" class="btn btn-primary">Zu den Einstellungen</a>&nbsp;
			{% else %}
				<a href="{% url 'login' %}" class="btn btn-success">Einloggen</a>&nbsp;
				<a href="{% url 'register' %}" class="btn btn-warning">Registrieren</a>&nbsp;
			{% endif %}
			<a href="{% url 'startpage' %}" class="btn btn-danger">Zurück zur Auswahl</a>
		</p>
	</div>
	{% endblock %}

templates/lotto/logged.html
{% extends "lotto/basis.html" %}
	{% load staticfiles %}
	{% block content %}
		{% if not user.is_authenticated %}
			<div class="alert alert-success" role="alert">
			  <h1>Herzlich Willkommen!</h1>
			  <p>Sie haben sich erfolgreich eingeloggt!</p>
			</div>
			<script>
			window.setTimeout('window.location = "/"',2000);
			</script>
		{% else %}
			<div class="alert alert-warning" role="alert">
			  <h1>Auf Wiedersehen!</h1>
			  <p>Sie haben sich erfolgreich ausgeloggt!</p>
			</div>
			<script>
			window.setTimeout('window.location = "/"',2000);
			</script>
		{% endif %}
	{% endblock %}

templates/lotto/login.html
{% extends "lotto/basis.html" %}
	{% load staticfiles %}
	{% block content %}
		{% if user.is_authenticated %}
			<div class="alert alert-success" role="alert">
			  <h1>Herzlich Willkommen!</h1>
			  <p>Sie haben sich erfolgreich eingeloggt!</p>
			</div>
			<script>
			window.setTimeout('window.location = "/"',2000);
			</script>
		{% else %}
			<div class="panel panel-default">
			  	<div class="panel-heading">
					<h3 class="panel-title">Benuzterlogin</h3>
			  	</div>
			  	<div class="panel-body">
			    	<form action="{% url 'dologin' %}" method="POST">
			    		{% csrf_token %}
			    		<div class="form-group">
			    			<label for="name">Benutzername:</label>
			    			<input name="name" id="name" placeholder="Benutzername" type="text" class="form-control" />
			    		</div>
			    		<div class="form-group">
			    			<label for="pw1">Passwort</label>
			    			<input name="pw1" id="pw1" placeholder="Passwort" type="password" class="form-control" />
			    		</div>
			    		<button id="sub" type="submit" class="btn btn-success">Anmelden</button>
			    	</form>
			  	</div>
			</div>
		{% endif %}
	{% endblock %}

templates/lotto/register.html
{% extends "lotto/basis.html" %}
	{% load staticfiles %}
	{% block content %}
		<div class="panel panel-default">
		  	<div class="panel-heading">
				<h3 class="panel-title">Registrierung</h3>
		  	</div>
		  	<div class="panel-body">
		    	<form action="{% url 'doreg' %}" method="POST">
		    		{% csrf_token %}
		    		<div class="form-group">
		    			<label for="name">Benutzername:</label>
		    			<input name="name" id="name" placeholder="Benutzername" type="text" class="form-control" />
		    			<small id="check_login"></small>
		    		</div>
		    		<div class="form-group">
		    			<label for="email">E-Mailadresse</label>
		    			<input name="email" id="email" placeholder="E-Mail" type="email" class="form-control" />
		    			<small id="check_email"></small>
		    		</div>
		    		<div class="form-group">
		    			<label for="pw1">Passwort</label>
		    			<input name="pw1" id="pw1" placeholder="Passwort" type="password" class="form-control" />
		    			<small class="check_pw"></small>
		    		</div>
		    		<div class="form-group">
		    			<label for="pw2">Passwort (wiederholen)</label>
		    			<input name="pw2" id="pw2" placeholder="Passwort wiederholen" type="password" class="form-control" />
		    			<small class="check_pw"></small>
		    		</div>
		    		<button id="sub" type="submit" class="btn btn-success">Registrieren</button>
		    	</form>
		  	</div>
		</div>
	{% endblock %}
	{% block scripts %}
		<script type="text/javascript" src="{% static "js/login.js" %}"></script>
	{% endblock %}

templates/lotto/settings.html
{% extends "lotto/basis.html" %}
	{% load staticfiles %}
	{% block content %}
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Benutzereinstellungen: {{login}} {% if trust == True %}[ <a role="button" data-toggle="collapse" href="#edit" aria-expanded="false" aria-controls="edit">bearbeiten</a> ] {% endif %}</h3>
			</div>
			<div class="panel-body">
				<ul class="list-group">
					<li class="list-group-item"><span class="badge">{{login}}</span>Benutzername:</li>
					<li class="list-group-item"><span class="badge">{{email}}</span>Email:</li>
					<li class="list-group-item"><span class="badge">{{lastvisit}}</span>Letzer Besuch:</li>
					<li class="list-group-item"><span class="badge">{{regdate}}</span>Registriert am:</li>
				</ul>
				{% if trust == True %}
					<div class="collapse" id="edit">
						<div class="alert alert-warning">
							<h1>Keine Angst!</h1>
							<p>Diesen Bereich kannst nur du(!) sehen!</p>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading">
								<h3 class="panel-title">Benuztereinstellungen bearbeiten</h3>
					  		</div>
			  				<div class="panel-body"></div>
								<form action="{% url 'doedit' %}" method="POST">
									{% csrf_token %}
									<div class="form-group">
										<label for="email">Ihre Email</label>
										<input name="email" type="email" id="email" value="{{email}}" class="form-control" />
										<small id="echeck"></small>
									</div>
									<div class="form-group">
										<label for="pw">Ihr neues Passwort</label>
										<div>
											<input name="pw" type="password" id="pw" placeholder="Ihr neues Passwort" class="form-control col-md-6" style="width:49%;float: left;" />
											<div style="width:2%;float: left;">&nbsp;</div>
											<input name="pw2" type="password" id="pw2" placeholder="Ihr neues Passwort (wiederholen)" class="form-control col-md-6" style="width:49%;float: left;" />
										</div>
										<small id="pw_stat"></small>
										<div class="clearfix"></div>
									</div>
									<div class="form-group">
										<label for="de">Wieviel Felder in der 6 aus 49 Lotterie (Deutschland)?</label>
										<input name="de" type="number" id="de" value="{{de}}" class="form-control" />
										<small id="de-filter"></small>
									</div>
									<div class="form-group">
										<label for="ziehung">Welche Tage sollen bei dem Vergleich in Betracht gezogen werden? (Deutschland)</label>
										<select name="ziehung" id="ziehung" class="form-control"></select>
										<small id="de-filter"></small>
									</div>
									<div class="form-group">
										<label for="eu">Wieviel Felder in der 5 aus 50 Lotterie? (Europa)</label>
										<input name="eu" type="number" id="eu" value="{{eu}}" class="form-control" />
										<small id="eu-filter"></small>
									</div>
									<input type="hidden" name="user_login" value="{{login}}">
									<input type="submit" value="Speichern" class="btn btn-success" />
								</form>
							</div>
						</div>
					</div>
				{% endif %}
			</div>
		</div>
	{% endblock %}
	{% block scripts %}
		<script src="http://static.maxim-harder.de/extra/gritter/jquery.gritter.min.js"></script>
		<script>
			var zieh = {{ziehung}}
		</script>
		<script src="{% static 'js/settings.js' %}"></script>
	{% endblock %}

templates/lotto/start.html
<!DOCTYPE html>
<html lang="de">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{title}}</title>
    <meta name="description" content="{{description}}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">
    <link href="{% static 'css/bootstrap-purple-blue.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Lato:100,300,400,700,100italic,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body>
	<div class="container">
		<div class="kasten">
			<h1>Wähle eine der beiden Lotterien</h1>
			<ul class="wahl">
				<li><a href="/de/"><img src="{% static 'images/deutschland.png' %}" class="img-responsive"></a></li>
				<li><a href="/eu/"><img src="{% static 'images/europa.png' %}" class="img-responsive"></a></li>
			</ul>
		</div>
	</div>
    <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script type="text/javascript" src="{% static "js/jquery-ui.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
</body>

</html>